### ISSUE TITLE
How to subscribe to events like Navigation.addListener("didFocus") ?

### ISSUE THREAD

**Issue by Natim** [reason-react-native/navigation#8]
How to subscribe to the navigation events?

https://reactnavigation.org/docs/en/navigation-events.html

**Comment by Natim** [comment]
Founded the todo: https://github.com/reason-react-native/navigation/blob/master/src/Navigation.re#L17

**Comment by Natim** [comment]
And there is the expected types: https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by cknitt** [comment]
Thanks for your contribution (#9). 👍
